### ISSUE TITLE
Update UI of Placement Daemon

### ISSUE THREAD

**Issue by yash1ts** [yash1ts/mailer-daemon#17]
**Is your feature request related to a problem? Please describe.**
Change the UI of placement daemon according to the design
![ui_md1](https://user-images.githubusercontent.com/45488341/86789929-7d160580-c085-11ea-9759-fdf627948885.png)

**Describe the solution you'd like**
For now no need to make the tabs, we can include them later. Make a new fragment for this and use it in the present activity. This UI is similar to other daemon UI (like campus demon) and so it will be reused at many places. Receive data at activity and pass it to fragment.

**Additional context**
Please use the Constraint layout and follow other guidelines. [Material design](https://material.io/develop/android)

**Comment by aashisha25** [comment]
Sir, I wish to work on this.

**Comment by yash1ts** [comment]
Go ahead. If you don't understand anything ask me.
