### ISSUE TITLE
Make the Clubs Page offline 

### ISSUE THREAD

**Issue by yash1ts** [yash1ts/mailer-daemon#23]
**Is your feature request related to a problem? Please describe.**
Clubs page gets data from firebase, but since clubs don't change that often we should make this offline. Something like hardcoding them.

**Describe the solution you'd like**
Download the current database as a json file and put it in assets and for icons use facebook URL links. then we can easily load the json file and clubs data.

**Additional context**
Since we are changing this file, it should be in kotlin. No need to change the Ui. Remove other methods which enable adding clubs and editing them.

**Comment by DhruvWalia03** [comment]
I would like to work on this sir

**Comment by yash1ts** [comment]
Ok, ask me if there is any confusion.
